language: python
script: python manage.py
language:
  - python
before-install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install black
script:
  - black --check .
  - flake8 --max-line-length=92

after_success:
  - coveralls